language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
before_deploy: npm run build
deploy:
  provider: npm
  email: trembl.ben@gmail.com
  api_key:
    secure: iOCCqvMy1BHUh+wb+FtVtwvtwGU01p7gj79FtQH8pNvsKVOZP/1bzyzKrVxlKmQ6Hc8kA3N9Mgg2BKhikHjJq0TZuFaFanmpYoCcsarjY0Tq4tR11dpAIUMdQk4awgJ2DWbvP7vyGP1KFiukC4NaSKVomtdyeZGoi/V891wEY7I=
  on:
    tags: true
    repo: thereactivestack/react-cookie
    node: '6'
