language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
before_deploy: npm run build
deploy:
  provider: npm
  email: gupta_dheeraj91@yahoo.com
  on:
    tags: true
    repo: dkumar1991/javascript-cookies
    node: '6'
